import type { ShapeTemplate } from '../engine/types'
import { revolveDefaults } from './revolveShapes'

function template(
  id: string,
  name: string,
  description: string,
  overrides: Record<string, number | string | boolean>,
): ShapeTemplate {
  return { id, name, description, values: { ...revolveDefaults, ...overrides } }
}

export const revolveTemplates: ShapeTemplate[] = [
  template('lamp-shade', 'Lamp Shade', 'An open-ended revolved shade. Light passes through top and bottom.', {
    height: 220,
    bottomDiameter: 220,
    topDiameter: 140,
    bottomMode: 'open',
    topMode: 'open',
    wallThickness: 2,
    sides: 64,
    color: '#f5e6c8',
  }),
  template('vase', 'Vase', 'A solid-bottomed, open-top vessel. Holds water.', {
    height: 240,
    bottomDiameter: 110,
    topDiameter: 90,
    bottomMode: 'solid',
    topMode: 'open',
    curveStyle: 'bulge',
    curveAmount: 30,
    wallThickness: 2.4,
    sides: 72,
    color: '#8fb7a8',
  }),
  template('planter', 'Planter / Pot', 'A sturdy, wide-mouthed pot with a solid base.', {
    height: 150,
    bottomDiameter: 140,
    topDiameter: 180,
    bottomMode: 'solid',
    topMode: 'open',
    wallThickness: 3,
    sides: 56,
    color: '#c96a4b',
  }),
  template('tumbler', 'Tumbler / Cup', 'A drinkware-scale vessel. Try low "smoothness" for a faceted look.', {
    height: 110,
    bottomDiameter: 75,
    topDiameter: 82,
    bottomMode: 'solid',
    topMode: 'open',
    wallThickness: 2.5,
    sides: 64,
    color: '#4a6fa5',
  }),
  template('twisted-spire', 'Twisted Spire', 'A faceted, spiraling sculptural form. Great as a candle holder or pen pot.', {
    height: 260,
    bottomDiameter: 90,
    topDiameter: 55,
    bottomMode: 'solid',
    topMode: 'open',
    twist: 240,
    wallThickness: 1.8,
    sides: 7,
    color: '#b892d6',
  }),
  template('wave-bowl', 'Wave Bowl', 'A wide, shallow dish with a rippling, fluted rim.', {
    height: 70,
    bottomDiameter: 80,
    topDiameter: 280,
    bottomMode: 'solid',
    topMode: 'open',
    curveStyle: 'bulge',
    curveAmount: 15,
    textureStyle: 'waves',
    textureAmount: 10,
    textureFrequency: 9,
    textureSpiral: 1.5,
    wallThickness: 2.5,
    sides: 96,
    color: '#5aa9a3',
  }),
  template('organic-pod', 'Organic Pod', 'A closed, coral/seed-pod-like sculptural form. Not a container — fully sealed.', {
    height: 160,
    bottomDiameter: 30,
    topDiameter: 30,
    bottomMode: 'solid',
    topMode: 'solid',
    curveStyle: 'bulge',
    curveAmount: 55,
    twist: 60,
    textureStyle: 'organic',
    textureAmount: 6,
    textureFrequency: 5,
    wallThickness: 2,
    sides: 80,
    color: '#e0824a',
  }),
  template(
    'flower-vase',
    'Flower Vase',
    'A vase whose cross-section is a Gielis superformula curve instead of a circle — petals, not a circle.',
    {
      height: 220,
      bottomDiameter: 90,
      topDiameter: 70,
      bottomMode: 'solid',
      topMode: 'open',
      curveStyle: 'bulge',
      curveAmount: 25,
      twist: 30,
      crossSectionStyle: 'superformula',
      sfM: 5,
      sfN1: 0.6,
      sfN2: 1.6,
      sfN3: 1.6,
      wallThickness: 2,
      sides: 120,
      color: '#e8a1c4',
    },
  ),
  template('gear-planter', 'Gear Planter', 'A planter with a toothed, mechanical superformula cross-section — cogs, not curves.', {
    height: 140,
    bottomDiameter: 140,
    topDiameter: 170,
    bottomMode: 'solid',
    topMode: 'open',
    crossSectionStyle: 'superformula',
    sfM: 10,
    sfN1: 14,
    sfN2: 3,
    sfN3: 3,
    wallThickness: 3,
    sides: 160,
    color: '#7a8b99',
  }),
  template(
    'lamp-base',
    'Lamp Base',
    'A hollow, weighted base for a table lamp. Open top sized for a standard socket/harp riser; open bottom routes the cord.',
    {
      height: 200,
      bottomDiameter: 140,
      topDiameter: 32,
      bottomMode: 'open',
      topMode: 'open',
      curveStyle: 'bulge',
      curveAmount: 30,
      wallThickness: 3.5,
      sides: 72,
      color: '#c9a876',
    },
  ),
  template(
    'honeycomb-lamp-shade',
    'Honeycomb Lamp Shade',
    'A lamp shade with real cut-through hexagonal holes — light shines straight through the honeycomb pattern.',
    {
      height: 220,
      bottomDiameter: 200,
      topDiameter: 150,
      bottomMode: 'open',
      topMode: 'open',
      perforationStyle: 'hexagon',
      perforationCellSize: 18,
      perforationHoleRatio: 0.8,
      wallThickness: 3,
      sides: 96,
      color: '#e8dcc4',
    },
  ),
]
